-- 由已审阅的Word草案转换的16类v1预案。只插入不存在的版本，不覆盖人工维护内容。
START TRANSACTION;
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-DT01','DT01','崩塌（落石）',1,1,CAST('["落石/土方覆盖车道数与估算方量","边坡是否仍掉块","上方裂缝、危岩和降雨","人员车辆受困","上下行可用车道","邻近桥隧及管线"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【落石/土方覆盖车道数与估算方量；边坡是否仍掉块；上方裂缝、危岩和降雨；人员车辆受困；上下行可用车道；邻近桥隧及管线。】。在事实尚未核清前，对相关内容统一标记为“待核实”。立即在安全距离外双向警戒并禁止人员进入落石轨迹区。核查伤亡、受困车辆和持续落石迹象，必要时请求消防、医疗。

现场初步控制后，按照“先隔离二次坠落危险区，再完成地质研判、人员搜救、清方保通和坡面临时防护。”组织处置。在【地点/桩号】设置【封控范围】，先完成【人员搜救/风险排查】。经地质技术组确认【进入条件】后，投入【数据库分配资源】清理约【待核实方量】土石方；采取【边坡临时防护措施】，于【复核时点】评估【单幅/全部】恢复通行。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，由地质技术人员确认可进入条件后，分层清理并保持观察哨。先抢通应急通道，再评估是否恢复单幅或全部通行。如出现以下情形，应及时调整方案并重新上报：【持续降雨、夜间或边坡仍不稳定：扩大封控并增配地质监测、照明；全幅阻断：组织绕行和跨市抢险；存在大型危岩：由专业队伍评估机械清除或受控处置。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"TRAFFIC_CONTROL_TEAM","quantity":2,"purpose":"双向封控和分流","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":6,"purpose":"上游预警和危险区隔离","mode":"BASE"},{"resourceTypeCode":"GEOLOGICAL_TEAM","quantity":1,"purpose":"危岩和边坡稳定性研判","mode":"BASE"},{"resourceTypeCode":"ROAD_RESCUE_TEAM","quantity":2,"purpose":"清方和临时防护","mode":"BASE"},{"resourceTypeCode":"EXCAVATOR","quantity":2,"purpose":"土石方清理","mode":"BASE"},{"resourceTypeCode":"LOADER","quantity":2,"purpose":"装载土石方","mode":"BASE"},{"resourceTypeCode":"DUMP_TRUCK","quantity":4,"purpose":"外运清理物","mode":"BASE"},{"resourceTypeCode":"MOBILE_LIGHTING","quantity":2,"purpose":"夜间或低照度作业时增配","mode":"CONDITIONAL"}]' AS JSON),'5d1e53d9a1d1dfc3f5d564430b2f4ed371ca2e43b4097af3e728e803af302e66','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-DT02','DT02','滑坡（坡体位移）',1,1,CAST('["裂缝位置和变化速率","坡脚鼓胀、渗水","路面/挡墙变形","降雨与地下水","影响车道和建筑","人员受威胁范围"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【裂缝位置和变化速率；坡脚鼓胀、渗水；路面/挡墙变形；降雨与地下水；影响车道和建筑；人员受威胁范围。】。在事实尚未核清前，对相关内容统一标记为“待核实”。划定滑坡体、影响区和安全观察点，停止坡脚开挖及无关机械作业。排查人员、车辆、房屋和管线受威胁情况并及时转移。

现场初步控制后，按照“避免人员进入潜在滑动区，持续监测变形，组织转移、交通管制和专业稳定性研判。”组织处置。对【地点】疑似滑坡区实施【封控/转移】，记录裂缝与位移【监测方式及频次】。地质技术组研判【稳定性结论待填】后，按批准措施开展【截排水/反压/临时防护】，在【复核条件】满足后分阶段恢复通行。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，布设裂缝/位移观察并记录时间序列，由地质技术组研判。在专业意见下实施截排水、反压或临时防护，不得盲目削坡。如出现以下情形，应及时调整方案并重新上报：【位移加速或强降雨：扩大撤离和全幅封闭；影响桥隧结构：同步结构检测；短期无法稳定：建立长期绕行和连续监测。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"TRAFFIC_CONTROL_TEAM","quantity":2,"purpose":"封控受威胁路段","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":6,"purpose":"设置滑坡影响区警示","mode":"BASE"},{"resourceTypeCode":"GEOLOGICAL_TEAM","quantity":2,"purpose":"位移监测和稳定性研判","mode":"BASE"},{"resourceTypeCode":"ROAD_RESCUE_TEAM","quantity":2,"purpose":"截排水和临时防护","mode":"BASE"},{"resourceTypeCode":"EXCAVATOR","quantity":1,"purpose":"按专业意见实施土方作业","mode":"BASE"},{"resourceTypeCode":"LOADER","quantity":1,"purpose":"装载处置材料","mode":"BASE"},{"resourceTypeCode":"DUMP_TRUCK","quantity":2,"purpose":"材料和弃方运输","mode":"BASE"},{"resourceTypeCode":"MOBILE_LIGHTING","quantity":2,"purpose":"夜间监测和作业时增配","mode":"CONDITIONAL"}]' AS JSON),'498ea593ac905f1182f49fa4d7b3b778542bced2ccc0ab5d10c862546ac98608','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-DT03','DT03','泥石流',1,1,CAST('["沟谷来水和泥砂变化","上游降雨、堰塞与物源","淤埋长度/厚度","人员车辆受困","桥涵堵塞","可能再次下泄时间窗"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【沟谷来水和泥砂变化；上游降雨、堰塞与物源；淤埋长度/厚度；人员车辆受困；桥涵堵塞；可能再次下泄时间窗。】。在事实尚未核清前，对相关内容统一标记为“待核实”。封锁沟口、冲沟和下游扇形危险区，人员向高处和两侧撤离。安排上游安全观察和通信联络，未经确认不得进入沟道。

现场初步控制后，按照“迅速撤离沟口与下游危险区，监测上游，防范二次泥石流，在安全窗口清淤抢通。”组织处置。立即封控【沟口/下游范围】并将人员转移至【安全位置】，由观察哨监测【上游来水、泥砂和降雨】。在确认【安全窗口】后，使用【数据库分配资源】分段清淤、疏通桥涵，达到【验收条件】后恢复应急通道。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，核查桥涵堵塞及堰塞风险，禁止直接破堵引发突泄。安全窗口内从下游或安全侧分段清淤，保持排水通道。如出现以下情形，应及时调整方案并重新上报：【上游持续强降雨或报警：停止作业并撤至安全区；桥涵被堵：组织水利/地质联合研判；全线淤埋：跨市调集装运设备并设置长期绕行。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"TRAFFIC_CONTROL_TEAM","quantity":2,"purpose":"封控沟口和下游危险区","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":8,"purpose":"多点预警和撤离引导","mode":"BASE"},{"resourceTypeCode":"GEOLOGICAL_TEAM","quantity":1,"purpose":"上游物源和二次风险研判","mode":"BASE"},{"resourceTypeCode":"ROAD_RESCUE_TEAM","quantity":2,"purpose":"清淤和排水抢通","mode":"BASE"},{"resourceTypeCode":"EXCAVATOR","quantity":2,"purpose":"分段清淤","mode":"BASE"},{"resourceTypeCode":"LOADER","quantity":2,"purpose":"装载淤积物","mode":"BASE"},{"resourceTypeCode":"DUMP_TRUCK","quantity":6,"purpose":"外运泥砂石块","mode":"BASE"},{"resourceTypeCode":"MOBILE_LIGHTING","quantity":2,"purpose":"夜间安全窗口作业时增配","mode":"CONDITIONAL"}]' AS JSON),'004569d77fcec135c6d59cf9e8cc91e0fa6005ed2f6334861a6b4db7e27ce840','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-DT04','DT04','沉陷与塌陷',1,1,CAST('["坑洞尺寸和扩展","地下空洞/管线","路基裂缝","车辆坠入与伤亡","相邻桥涵","积水和冲刷","可用车道承载情况"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【坑洞尺寸和扩展；地下空洞/管线；路基裂缝；车辆坠入与伤亡；相邻桥涵；积水和冲刷；可用车道承载情况。】。在事实尚未核清前，对相关内容统一标记为“待核实”。对塌陷边缘外扩设置硬隔离，禁止机械和人员靠近未探明区域。核查坠入车辆、人员和地下管线，优先搜救并防止燃气/电力次生风险。

现场初步控制后，按照“防止车辆坠落和二次坍塌，查明空洞范围，组织搜救、临时支护和结构性修复。”组织处置。在【塌陷点】外扩【安全距离待专业确认】设置隔离，完成【人员/车辆搜救及管线核查】。通过【探测手段】确定空洞范围后，按【加固方案】回填处治；经【承载/结构检测】合格后分阶段恢复通行。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，开展空洞和路基结构探测，确定安全作业边界。按专业方案回填、加固并检测承载能力后再恢复通行。如出现以下情形，应及时调整方案并重新上报：【坑洞快速扩大：扩大封闭并疏散；涉及车辆吊救：配置吊装与消防；地下管线异常：通知权属单位；夜间作业：增配照明和观察。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"TRAFFIC_CONTROL_TEAM","quantity":2,"purpose":"封闭塌陷影响区","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":6,"purpose":"设置硬隔离和上游预警","mode":"BASE"},{"resourceTypeCode":"GEOLOGICAL_TEAM","quantity":1,"purpose":"空洞和路基稳定性研判","mode":"BASE"},{"resourceTypeCode":"ROAD_RESCUE_TEAM","quantity":2,"purpose":"支护、回填和加固","mode":"BASE"},{"resourceTypeCode":"EXCAVATOR","quantity":1,"purpose":"安全边界确认后的开挖处置","mode":"BASE"},{"resourceTypeCode":"LOADER","quantity":1,"purpose":"回填材料装载","mode":"BASE"},{"resourceTypeCode":"DUMP_TRUCK","quantity":3,"purpose":"回填材料运输","mode":"BASE"},{"resourceTypeCode":"CRANE","quantity":1,"purpose":"存在坠入车辆或大型构件时增配","mode":"CONDITIONAL"}]' AS JSON),'fb83d7f7c49b223a38ca95f560359a03bdec735b1869c0c9c0015b7837c38c30','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-DT05','DT05','水毁',1,1,CAST('["水深、流速和变化","积水/冲毁长度","路基掏空","桥涵水位与漂浮物","受困人员车辆","降雨趋势","可用绕行路线"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【水深、流速和变化；积水/冲毁长度；路基掏空；桥涵水位与漂浮物；受困人员车辆；降雨趋势；可用绕行路线。】。在事实尚未核清前，对相关内容统一标记为“待核实”。封闭超过安全条件或无法判断深度的积水路段，禁止车辆试探通行。优先转移受困人员，远离急流、临水边坡和带电设施。

现场初步控制后，按照“避免人员车辆涉险，组织排水、抢险和结构检查，防止冲刷扩大并尽快恢复安全通行。”组织处置。封控【地点/受影响方向】并转移【受困情况】，持续记录水深和变化。投入【数据库分配资源】疏通【边沟/涵洞】、实施排水及路基防护；经【路基/桥涵检查】确认后，按【恢复条件】开放通行。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，疏通边沟、涵洞并布设排水设备，防止排水冲击下游。检查路基掏空和桥涵基础，确认结构安全后恢复交通。如出现以下情形，应及时调整方案并重新上报：【水位持续上涨：扩大封控并请求防汛联动；路基冲毁：投入抢险、装运设备构筑临时通道；桥涵异常：暂停通行并开展专项检测。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"TRAFFIC_CONTROL_TEAM","quantity":2,"purpose":"封控积水或冲毁路段","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":6,"purpose":"涉水风险警示和绕行引导","mode":"BASE"},{"resourceTypeCode":"ROAD_RESCUE_TEAM","quantity":2,"purpose":"排水、抢险和临时防护","mode":"BASE"},{"resourceTypeCode":"DRAINAGE_PUMP","quantity":4,"purpose":"排除路面积水","mode":"BASE"},{"resourceTypeCode":"LOADER","quantity":1,"purpose":"清理淤积和装载材料","mode":"BASE"},{"resourceTypeCode":"DUMP_TRUCK","quantity":3,"purpose":"抢险材料运输","mode":"BASE"},{"resourceTypeCode":"MOBILE_LIGHTING","quantity":2,"purpose":"夜间排水抢险时增配","mode":"CONDITIONAL"},{"resourceTypeCode":"AMBULANCE","quantity":1,"purpose":"存在人员受困或受伤时增配","mode":"CONDITIONAL"}]' AS JSON),'861d5da94b7edce5230ffd1d4bcf0c84bb2b7326d5a33f89845279be3944be97','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-ET101','ET101','拥堵',1,1,CAST('["排队长度和增长趋势","平均速度","起止点和方向","诱因","应急车道状态","服务区容量","可分流节点","特殊车辆滞留"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【排队长度和增长趋势；平均速度；起止点和方向；诱因；应急车道状态；服务区容量；可分流节点；特殊车辆滞留。】。在事实尚未核清前，对相关内容统一标记为“待核实”。巡查确认拥堵起点、诱因和是否伴随事故/障碍。保持应急车道与救援通道畅通，设置上游预警。

现场初步控制后，按照“快速查明诱因，保护应急通道，实施分流疏导并持续发布真实路况。”组织处置。巡查确认【路段/方向】拥堵由【已核实诱因/待核实】引起，当前排队约【实测长度】。在【节点】实施【分流/匝道控制/间歇放行】，保持应急车道畅通，并以【频次】更新速度、队尾和解除条件。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，在可控节点实施分流、匝道调节或间歇放行。持续监测排队消散，避免次生追尾。如出现以下情形，应及时调整方案并重新上报：【排队快速增长或影响枢纽：扩大分流范围；高温/严寒长时滞留：协调基本保障；伴随事故/火灾：切换主事件预案并保留拥堵影响。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"TRAFFIC_CONTROL_TEAM","quantity":2,"purpose":"分流和入口控制","mode":"BASE"},{"resourceTypeCode":"ROAD_PATROL_TEAM","quantity":2,"purpose":"核查队尾、诱因和应急车道","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":6,"purpose":"动态队尾预警","mode":"BASE"},{"resourceTypeCode":"TOW_TRUCK","quantity":1,"purpose":"快速移除故障车辆","mode":"BASE"},{"resourceTypeCode":"MOBILE_LIGHTING","quantity":2,"purpose":"夜间拥堵处置时增配","mode":"CONDITIONAL"}]' AS JSON),'bffaa2cae5ca647397b8968e9923c5544ca05956acdeda877f61a709aaa6b952','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-ET102','ET102','明火（火灾）',1,1,CAST('["燃烧对象","危险品标识","人员被困","风向/隧道通风","爆炸风险","火势范围","上游来车","消防水源和疏散方向"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【燃烧对象；危险品标识；人员被困；风向/隧道通风；爆炸风险；火势范围；上游来车；消防水源和疏散方向。】。在事实尚未核清前，对相关内容统一标记为“待核实”。立即报警并双向封控，禁止无防护人员接近或自行处置未知危险品。组织人员向上风向或安全出口疏散，清点受困情况。

现场初步控制后，按照“人员生命优先，快速报警、隔离、疏散和灭火，防止爆炸、烟气和交通次生事故。”组织处置。对【地点/方向】实施双向封控，组织人员沿【经现场确认的安全方向】疏散。消防救援处置【燃烧对象】，医疗力量救治【已核实伤情】；完成【测温/排烟/复燃监测/结构检查】后再评估恢复通行。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，为消防建立逆向救援通道，医疗力量在安全区待命。灭火后持续测温、排烟和复燃监测，确认结构安全。如出现以下情形，应及时调整方案并重新上报：【隧道内火灾：按隧道疏散和通风策略执行；疑似危险品：扩大隔离并请求专业处置；火势蔓延至林地/设施：联动相关部门。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"TRAFFIC_CONTROL_TEAM","quantity":2,"purpose":"双向封控和救援通道保障","mode":"BASE"},{"resourceTypeCode":"ROAD_PATROL_TEAM","quantity":2,"purpose":"疏散和上游警戒","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":8,"purpose":"扩大火场警示范围","mode":"BASE"},{"resourceTypeCode":"FIRE_RESCUE_TEAM","quantity":2,"purpose":"灭火、破拆和防复燃","mode":"BASE"},{"resourceTypeCode":"AMBULANCE","quantity":2,"purpose":"伤员救治和转运","mode":"BASE"},{"resourceTypeCode":"MOBILE_LIGHTING","quantity":2,"purpose":"夜间救援照明","mode":"CONDITIONAL"}]' AS JSON),'e37f2a9836660021eecf5880a1962977b8435ebf54d325f1828d2d6bbbdf1a12','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-ET103','ET103','抛撒物',1,1,CAST('["物料种类、范围和厚度","是否危险化学品/油污","来源车辆","影响车道","路面附着和打滑","上游交通","排水口污染风险"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【物料种类、范围和厚度；是否危险化学品/油污；来源车辆；影响车道；路面附着和打滑；上游交通；排水口污染风险。】。在事实尚未核清前，对相关内容统一标记为“待核实”。在上游设置渐进警示和车道封闭，禁止人员直接接触未知物料。识别物料及危险性，危险品或油污按专业要求升级处置。

现场初步控制后，按照“上游预警、识别物料风险、快速清障清洁并防止污染和车辆二次事故。”组织处置。在【上游距离】设置预警并封闭【车道】，确认抛撒物为【已核实物料/待核实】。投入【数据库分配资源】分段收集、装运和清洁路面，检查【残留/打滑/路面损伤】合格后恢复通行。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，从安全侧清理、装运并进行路面清洁防滑。巡查残留物和路面损伤后解除管制。如出现以下情形，应及时调整方案并重新上报：【跨多车道/长距离：分段封控和机械清理；油污或危险品：增大隔离并防止进入排水系统；夜间：增配照明。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"TRAFFIC_CONTROL_TEAM","quantity":2,"purpose":"封闭受影响车道","mode":"BASE"},{"resourceTypeCode":"ROAD_PATROL_TEAM","quantity":1,"purpose":"核查物料和来源车辆","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":6,"purpose":"渐进式上游警示","mode":"BASE"},{"resourceTypeCode":"ROAD_RESCUE_TEAM","quantity":1,"purpose":"清障和路面清洁","mode":"BASE"},{"resourceTypeCode":"LOADER","quantity":1,"purpose":"大量散落物机械收集","mode":"BASE"},{"resourceTypeCode":"DUMP_TRUCK","quantity":2,"purpose":"散落物合规外运","mode":"BASE"}]' AS JSON),'63eb8f12c11605e61d337fcad97b8ab2b0deb00c19ef7437118c4cac3d12e4b2','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-ET104','ET104','设备故障',1,1,CAST('["设备名称和编号","失效功能","影响范围","告警日志","供电/通信状态","冗余系统","隧道环境","人工接管条件"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【设备名称和编号；失效功能；影响范围；告警日志；供电/通信状态；冗余系统；隧道环境；人工接管条件。】。在事实尚未核清前，对相关内容统一标记为“待核实”。确认故障设备、影响功能和是否存在人身/电气危险。启用备用系统、人工值守或临时交通组织，避免关键安全功能空缺。

现场初步控制后，按照“隔离故障影响，启用安全降级或人工接管，修复设备并完成联动测试。”组织处置。确认【设备编号/功能】故障，影响【区域/功能】。立即启用【备用系统/人工接管】并设置【现场安全措施】；由设备抢修队伍完成【检修内容】及【单机/联动测试】，测试合格后恢复运行。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，留存告警和操作记录，由专业抢修人员断电/挂牌后检修。修复后完成单机及联动测试再恢复自动运行。如出现以下情形，应及时调整方案并重新上报：【隧道通风/消防等关键系统失效：限制或关闭通行；多系统同时故障：升级协调供电通信；短期无法修复：建立持续人工保障。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"ROAD_PATROL_TEAM","quantity":1,"purpose":"现场核查和临时交通保障","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":4,"purpose":"故障区域警示","mode":"BASE"},{"resourceTypeCode":"EQUIPMENT_REPAIR_TEAM","quantity":2,"purpose":"机电设备诊断和抢修","mode":"BASE"},{"resourceTypeCode":"TOW_TRUCK","quantity":1,"purpose":"涉及移动设备或车辆时增配","mode":"CONDITIONAL"}]' AS JSON),'91d51cabfa4b5248431e28abcef962404dff7609d9978751bd6f04ebbce3ea71','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-ET105','ET105','占用应急车道',1,1,CAST('["占用位置和长度","车辆/人员数量","是否故障或救援需要","救援车辆通行需求","主线交通状态","可安全驶离位置"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【占用位置和长度；车辆/人员数量；是否故障或救援需要；救援车辆通行需求；主线交通状态；可安全驶离位置。】。在事实尚未核清前，对相关内容统一标记为“待核实”。巡查核实占用性质，优先保障正在执行任务的救援车辆。设置上游警示，指导车辆在安全条件下有序驶离。

现场初步控制后，按照“快速核实原因、恢复应急通道、保护现场人员并避免强行并线造成次生事故。”组织处置。巡查确认【路段/方向】应急车道被【对象及原因】占用，在【位置】设置警示并引导有序驶离；对【故障车辆】安排拖移，确保【救援任务/应急通道】持续畅通。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，故障车辆转入ET107处置并安排拖移。恢复后持续巡查应急车道完整性。如出现以下情形，应及时调整方案并重新上报：【大范围连续占用：联动分段疏导；存在执法需求：依法移交；主线拥堵严重：同步采用ET101的队尾预警。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"ROAD_PATROL_TEAM","quantity":2,"purpose":"核查占用原因并引导驶离","mode":"BASE"},{"resourceTypeCode":"TRAFFIC_CONTROL_TEAM","quantity":1,"purpose":"保障救援车辆通行","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":4,"purpose":"上游警示和作业保护","mode":"BASE"},{"resourceTypeCode":"TOW_TRUCK","quantity":1,"purpose":"故障车辆无法驶离时增配","mode":"CONDITIONAL"}]' AS JSON),'3be4fa7586686bfc1892c6c17d6335112bbcc1de2e181bfc5ea110d62f2edbf0','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-ET106','ET106','交通事故',1,1,CAST('["车辆数和类型","人员伤亡/受困","危险品","事故位置和占道","泄漏/火灾","车流队尾","车辆稳定性","公安现场要求"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【车辆数和类型；人员伤亡/受困；危险品；事故位置和占道；泄漏/火灾；车流队尾；车辆稳定性；公安现场要求。】。在事实尚未核清前，对相关内容统一标记为“待核实”。立即报警，在上游设置足够预警并保护事故现场和应急通道。先评估车辆稳定、火灾、泄漏和来车风险，再实施救援。

现场初步控制后，按照“救人优先，防止追尾、火灾和泄漏，建立救援通道，完成清障和路面恢复。”组织处置。在【事故位置】上游实施【预警与封控】，建立救援通道。现场确认【车辆/伤亡/危险品】后，由【医疗/消防】先行救援，使用【数据库分配资源】完成清障、吊装和路面清理；经【现场联合确认】后恢复通行。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，医疗和消防优先救治、破拆；清障吊装服从现场统一指挥。清除车辆与散落物、处置污染并检查路面后恢复通行。如出现以下情形，应及时调整方案并重新上报：【人员被困/危化品/起火：升级消防医疗和隔离；重型车辆侧翻：增配吊装并编制安全方案；长队形成：同步启动拥堵疏导。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"TRAFFIC_CONTROL_TEAM","quantity":2,"purpose":"事故上游封控和分流","mode":"BASE"},{"resourceTypeCode":"ROAD_PATROL_TEAM","quantity":2,"purpose":"现场保护和队尾预警","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":8,"purpose":"事故区和救援通道警示","mode":"BASE"},{"resourceTypeCode":"TOW_TRUCK","quantity":2,"purpose":"事故车辆清障","mode":"BASE"},{"resourceTypeCode":"AMBULANCE","quantity":2,"purpose":"伤员救治和转运","mode":"BASE"},{"resourceTypeCode":"FIRE_RESCUE_TEAM","quantity":2,"purpose":"破拆、消防和危险排除","mode":"BASE"},{"resourceTypeCode":"CRANE","quantity":1,"purpose":"重型车辆侧翻或坠落时增配","mode":"CONDITIONAL"},{"resourceTypeCode":"MOBILE_LIGHTING","quantity":2,"purpose":"夜间事故救援","mode":"CONDITIONAL"}]' AS JSON),'bf0536501d10fbc3410b7cb14a4dccfaecc5dbc7806773cb0e679d42273fe5f2','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-ET107','ET107','异常停车',1,1,CAST('["停车位置和车道","车辆类型","人员情况","故障现象","是否可移动","后方视距","燃油/货物风险","最近安全停靠点"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【停车位置和车道；车辆类型；人员情况；故障现象；是否可移动；后方视距；燃油/货物风险；最近安全停靠点。】。在事实尚未核清前，对相关内容统一标记为“待核实”。提示车内人员在安全条件下撤至护栏外或安全区，不在车道逗留。布设上游警示并派巡查保护，夜间开启必要照明。

现场初步控制后，按照“立即保护车后区域和人员，将车辆安全移离行车区域并排除遗留风险。”组织处置。在【停车位置】上游设置【警示范围】，将【人员数量】引导至【安全区域】。确认车辆【可/不可】移动后，安排【自行驶离/数据库分配拖车】至【安全停靠点】，并检查【泄漏/遗留物】。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，评估车辆可否自行移动；不可移动时实施专业拖移。检查路面泄漏和遗留物后解除警示。如出现以下情形，应及时调整方案并重新上报：【大客车/危化品车辆：扩大保护并组织乘员疏散；隧道/弯道：加强入口控制；设备故障可现场修复时仍需保持防撞区。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"ROAD_PATROL_TEAM","quantity":1,"purpose":"保护停车区域和人员","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":4,"purpose":"上游防撞警示","mode":"BASE"},{"resourceTypeCode":"TOW_TRUCK","quantity":1,"purpose":"拖移无法行驶车辆","mode":"BASE"},{"resourceTypeCode":"EQUIPMENT_REPAIR_TEAM","quantity":1,"purpose":"可安全现场检修时增配","mode":"CONDITIONAL"}]' AS JSON),'28b779eb9c22b03c35d48cd9704823be665bfb9683f8ff36dfc06e3cc2f19030','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-ET108','ET108','浓雾检测',1,1,CAST('["实测能见度","雾区起止和变化","路面湿滑","风向","车流速度","事故情况","相邻站点数据","可控入口和分流点"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【实测能见度；雾区起止和变化；路面湿滑；风向；车流速度；事故情况；相邻站点数据；可控入口和分流点。】。在事实尚未核清前，对相关内容统一标记为“待核实”。巡查或多源数据核实雾区范围和实测能见度。在雾区上游提前预警，保持车距并控制进入流量。

现场初步控制后，按照“降低进入雾区的交通风险，通过预警、限速、间歇放行或封闭避免多车事故。”组织处置。经【巡查/设备】确认【路段】能见度约【实测值】，雾区范围为【起止点】。在【上游节点】实施【预警/限速/间歇放行/封闭】，每【频次】复测；达到【依据现行规定确认的解除条件】后逐级恢复。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，根据规定和现场指挥采取限速、间歇放行或临时封闭。持续复测，达到解除条件后逐级恢复。如出现以下情形，应及时调整方案并重新上报：【能见度继续下降或发生事故：立即收紧管制；跨路段团雾：多点协同控制；传感器冲突：以人工核查和可靠设备复核。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"ROAD_PATROL_TEAM","quantity":2,"purpose":"复核雾区和能见度","mode":"BASE"},{"resourceTypeCode":"TRAFFIC_CONTROL_TEAM","quantity":2,"purpose":"限速、间歇放行或封闭","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":8,"purpose":"雾区上游多点预警","mode":"BASE"},{"resourceTypeCode":"MOBILE_LIGHTING","quantity":2,"purpose":"收费站或管制节点照明","mode":"BASE"}]' AS JSON),'9630ca5240d04d9d0c7bd052de3f8fb2f38562cf5ab4ac1d23d5d2e43751aa33','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-ET109','ET109','路障',1,1,CAST('["障碍物材质、尺寸、重量和稳定性","来源","占道","是否带电/有毒/尖锐","可移动方式","上游交通","道路结构损伤"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【障碍物材质、尺寸、重量和稳定性；来源；占道；是否带电/有毒/尖锐；可移动方式；上游交通；道路结构损伤。】。在事实尚未核清前，对相关内容统一标记为“待核实”。在上游设置足够预警并封闭受影响车道。识别障碍物来源、稳定性及电气/危险物风险，未知时不得直接接触。

现场初步控制后，按照“建立防撞区，识别障碍风险，采用适配装备清除并检查道路设施。”组织处置。在【路障位置】上游设置【预警/封闭】，确认障碍物为【材质、尺寸及风险】。采用【拖移/切割/数据库分配吊装资源】清除，检查【路面、护栏、设备】无遗留风险后恢复通行。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，制定拖移、切割或吊装方案，确保机械支腿和作业空间安全。清除后巡查路面、护栏和附属设施。如出现以下情形，应及时调整方案并重新上报：【大型/不稳定构件：使用吊装并扩大封控；倒伏树木涉及电线：先由权属单位断电确认；多点路障：分段组织资源。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"ROAD_PATROL_TEAM","quantity":1,"purpose":"核查障碍物风险和来源","mode":"BASE"},{"resourceTypeCode":"TRAFFIC_CONTROL_TEAM","quantity":2,"purpose":"封闭受影响车道","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":6,"purpose":"建立上游防撞区","mode":"BASE"},{"resourceTypeCode":"ROAD_RESCUE_TEAM","quantity":1,"purpose":"切割、清障和设施检查","mode":"BASE"},{"resourceTypeCode":"TOW_TRUCK","quantity":1,"purpose":"可拖移障碍物处置","mode":"BASE"},{"resourceTypeCode":"CRANE","quantity":1,"purpose":"大型或不稳定障碍物时增配","mode":"CONDITIONAL"}]' AS JSON),'fa90eb591c912551693fae85afba4de49c995e4ec58a633d0b007a00265697ba','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-ET110','ET110','施工',1,1,CAST('["施工原因和许可","作业区长度","占道","机械设备","人员","交通组织","地下管线","夜间照明","预计工序（非承诺工期）"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【施工原因和许可；作业区长度；占道；机械设备；人员；交通组织；地下管线；夜间照明；预计工序（非承诺工期）。】。在事实尚未核清前，对相关内容统一标记为“待核实”。核实是否应急抢修及现场负责人，按要求设置施工控制区。完善上游预告、渐变、缓冲、作业和终止区域。

现场初步控制后，按照“规范作业区、隔离人车冲突，按批准工序实施抢修并保证交通组织连续。”组织处置。因【已核实抢修原因】在【地点】设置符合要求的施工控制区，占用【车道】。投入【数据库分配资源】按【工序】实施作业，采用【分流/交替通行/封闭绕行】组织交通；每完成【节点】进行安全复核。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，机械倒车、装运和人员作业设置专人指挥，检查地下管线。每个工序完成后检查道路和防护设施再调整交通。如出现以下情形，应及时调整方案并重新上报：【全幅封闭：启用绕行和跨部门协调；夜间/雨天：增强照明与防滑；工期延长：更新交通公告但不臆造结束时间。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"TRAFFIC_CONTROL_TEAM","quantity":2,"purpose":"施工控制区和分流","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":8,"purpose":"预告、渐变、缓冲和终止区","mode":"BASE"},{"resourceTypeCode":"ROAD_RESCUE_TEAM","quantity":2,"purpose":"应急抢修作业","mode":"BASE"},{"resourceTypeCode":"EXCAVATOR","quantity":1,"purpose":"土方或路基抢修","mode":"BASE"},{"resourceTypeCode":"LOADER","quantity":1,"purpose":"材料装载","mode":"BASE"},{"resourceTypeCode":"DUMP_TRUCK","quantity":3,"purpose":"材料运输和弃方外运","mode":"BASE"},{"resourceTypeCode":"MOBILE_LIGHTING","quantity":2,"purpose":"夜间施工照明","mode":"CONDITIONAL"}]' AS JSON),'1abb55b7e2998710e3efcfe54790364e65266ff0fd86abb708615b73d108eb88','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
INSERT IGNORE INTO w_emergency_response_plan (plan_id,event_type,event_type_name,plan_version,plan_status,required_facts,rescue_plan_template,resource_baseline,content_hash,source_document,activation_time,remarks,create_time,update_time) VALUES ('ERP-ET112','ET112','道路积雪',1,1,CAST('["积雪/冰层厚度","路面温度","降雪趋势","坡道桥面隧道口","摩擦状况","滞留车辆","封控节点","融雪物资使用限制"]' AS JSON),'接报事件【事件编号】后，现场处置人员立即赶赴【事件地点、路线、方向和桩号】，核实【积雪/冰层厚度；路面温度；降雪趋势；坡道桥面隧道口；摩擦状况；滞留车辆；封控节点；融雪物资使用限制。】。在事实尚未核清前，对相关内容统一标记为“待核实”。巡查确认积雪、结冰范围并优先控制桥面、长坡、弯道和隧道口。设置警示、限速和必要封闭，禁止不具备条件车辆进入。

现场初步控制后，按照“优先保障桥面、坡道和关键通道，实施除雪防滑与交通控制，防止侧滑和滞留。”组织处置。确认【路段】存在【积雪/结冰】，重点控制【桥面/坡道/弯道】。投入【数据库分配资源】按【作业顺序】除雪并投放【经批准的融雪/防滑物资】，实施【限速/封闭】；复测【路面状态】满足条件后逐级放行。具体资源从数据库实际可用库存中匹配，优先使用事件所在城市资源；本地不足时按距离调集邻近城市资源，并在方案中保留未满足的资源缺口。

作业过程中，机械除雪遵循先主线后匝道、先关键通道后一般路段。按环境和设施要求使用融雪防滑物资，复测路面后恢复。如出现以下情形，应及时调整方案并重新上报：【持续降雪：滚动作业和重复巡查；大范围结冰：跨市调集除雪车辆和物资；车辆滞留：组织拖移、疏导与必要保障。】。现场每【信息更新间隔】分钟更新一次【人员、风险、交通影响、资源到位和处置进展】；达到【本类型安全复核条件】并经【现场联合确认单位】确认后，按【分阶段开放方式】恢复通行。',CAST('[{"resourceTypeCode":"ROAD_PATROL_TEAM","quantity":2,"purpose":"巡查冰雪范围和重点部位","mode":"BASE"},{"resourceTypeCode":"TRAFFIC_CONTROL_TEAM","quantity":2,"purpose":"限速、封闭和分流","mode":"BASE"},{"resourceTypeCode":"WARNING_EQUIPMENT","quantity":8,"purpose":"冰雪路段预警","mode":"BASE"},{"resourceTypeCode":"SNOW_REMOVAL_VEHICLE","quantity":2,"purpose":"机械除雪","mode":"BASE"},{"resourceTypeCode":"DEICING_MATERIAL","quantity":4,"purpose":"经批准后实施融雪防滑","mode":"BASE"},{"resourceTypeCode":"LOADER","quantity":1,"purpose":"积雪装载和转运","mode":"BASE"},{"resourceTypeCode":"MOBILE_LIGHTING","quantity":2,"purpose":"夜间除雪照明","mode":"CONDITIONAL"}]' AS JSON),'330766a3ee690ba075e0b5be4e25fd8515958833591135fd47d2def72c1adfc6','福建公路应急事件分类与处置预案草案.docx',CURRENT_TIMESTAMP(6),'Demo已审阅版v1',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
COMMIT;
SELECT event_type,event_type_name,plan_version,plan_status,content_hash FROM w_emergency_response_plan ORDER BY event_type,plan_version;
